### ISSUE TITLE
CLI usage

### ISSUE THREAD

**Issue by Warths** [iminashi/ShowlightEditor#1]
Hello Iminashi
I just discovered your work and it's almost exactly what i was looking for.

I'm currently using Rocksmith 2014 Showlights to drive a real led panel array, that sync to the current song. 

The results are flawless on officials and some recent CDLC's, but a good portion of the CDLCs are packed using a very primitive version of a Showlight generator
I would like to be able to programmaticaly update those files with fresh showlights generated by this software.

Is there any way to use this software with command lines, and, if not, is it possible to add this feature ?

Something in this flavor could really help :
```
> ShowlightEditorCLI.exe 
        --FogSourceArrangement=/path/to/arr.xml
        --SpotlightSourceArrangement=/path/to/arr.xml
        --ChangeEvery=16 
        --UseCompatibleColors=true
        --Output=/path/to/output.xml
```

Thanks a lot for your work

**Comment by iminashi** [comment]
That's not currently possible, but I'll implement it.

**Comment by iminashi** [comment]
I've added a [CLI version of the generator](https://github.com/iminashi/ShowlightEditor/tree/master/ShowLightGenerator.CLI).

A Windows build can be [downloaded here](https://drive.google.com/file/d/1JtIqLUA1leO4PP5cg5bF7bggXwwWlqsT/view?usp=sharing).

**Comment by Warths** [comment]
Wow
I'm impressed by the responsiveness and quality of work
Thanks a lot !
